package app

import (
	"bufio"
	"bytes"
	"fmt"
	"io/fs"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"text/template"
	"time"

	"github.com/google/uuid"
	"github.com/jdillenberger/homelabctl/internal/config"
	"github.com/jdillenberger/homelabctl/internal/exec"
	"gopkg.in/yaml.v3"
)

// DeployedRouting holds per-app routing state.
type DeployedRouting struct {
	Enabled       bool     `yaml:"enabled"`
	Domains       []string `yaml:"domains"`
	ContainerPort int      `yaml:"container_port"`
	KeepPorts     bool     `yaml:"keep_ports"`
}

// DeployedApp holds information about a deployed app instance.
type DeployedApp struct {
	Name       string            `yaml:"name"`
	Template   string            `yaml:"template"`
	Values     map[string]string `yaml:"values"`
	DeployedAt time.Time         `yaml:"deployed_at"`
	Version    string            `yaml:"version"`
	Routing    *DeployedRouting  `yaml:"routing,omitempty"`
}

// DeployOptions holds parameters for a deploy operation.
type DeployOptions struct {
	Values  map[string]string
	DryRun  bool
	Confirm bool // if true, skip confirmation prompt
}

// Manager handles app lifecycle operations.
type Manager struct {
	cfg      *config.Config
	registry *Registry
	renderer *TemplateRenderer
	compose  *Compose
	runner   *exec.Runner

	OnDeploy func(appName string, routing *DeployedRouting)
	OnRemove func(appName string)
}

// NewManager creates a new app manager.
func NewManager(cfg *config.Config, runner *exec.Runner, tmplFS fs.FS) (*Manager, error) {
	registry, err := NewRegistry(tmplFS)
	if err != nil {
		return nil, fmt.Errorf("loading registry: %w", err)
	}

	return &Manager{
		cfg:      cfg,
		registry: registry,
		renderer: NewTemplateRenderer(registry),
		compose:  NewCompose(runner, cfg.Docker.ComposeCommand),
		runner:   runner,
	}, nil
}

// Registry returns the app template registry.
func (m *Manager) Registry() *Registry {
	return m.registry
}

// ensureNetwork creates the Docker network if it does not already exist.
func (m *Manager) ensureNetwork() error {
	network := m.cfg.Docker.DefaultNetwork
	// Try to create; if it already exists the error is harmless.
	if _, err := m.runner.Run(m.cfg.Docker.Runtime, "network", "create", network); err != nil {
		// Verify the network actually exists (it may have been created concurrently).
		if _, inspectErr := m.runner.Run(m.cfg.Docker.Runtime, "network", "inspect", network); inspectErr != nil {
			return fmt.Errorf("ensuring docker network %s: %w", network, err)
		}
	}
	return nil
}

// acquireLock takes an exclusive file lock to prevent concurrent operations on the same app.
// Returns the lock file which must be passed to releaseLock when done.
func (m *Manager) acquireLock(appName string) (*os.File, error) {
	lockDir := filepath.Join(m.cfg.AppsDir, ".locks")
	if err := os.MkdirAll(lockDir, 0o755); err != nil {
		return nil, fmt.Errorf("creating lock directory: %w", err)
	}
	lockPath := filepath.Join(lockDir, appName+".lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("opening lock file: %w", err)
	}
	if err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		f.Close()
		return nil, fmt.Errorf("app %s: another operation is in progress", appName)
	}
	return f, nil
}

// releaseLock releases the file lock and removes the lock file.
func (m *Manager) releaseLock(f *os.File) {
	_ = syscall.Flock(int(f.Fd()), syscall.LOCK_UN)
	name := f.Name()
	f.Close()
	os.Remove(name)
}

// Deploy deploys an app from its template with the given values.
func (m *Manager) Deploy(appName string, opts DeployOptions) error {
	lock, err := m.acquireLock(appName)
	if err != nil {
		return err
	}
	defer m.releaseLock(lock)

	meta, ok := m.registry.Get(appName)
	if !ok {
		return fmt.Errorf("unknown app template: %s", appName)
	}

	// Check if already deployed
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(filepath.Join(appDir, ".homelabctl.yaml")); err == nil {
		return fmt.Errorf("app %s is already deployed (remove first)", appName)
	}

	// Merge defaults into values
	mergedValues := make(map[string]string)
	for _, v := range meta.Values {
		if v.Default != "" {
			mergedValues[v.Name] = v.Default
		}
	}
	for k, v := range opts.Values {
		mergedValues[k] = v
	}

	// Auto-generate secrets
	autoGenerated := make(map[string]bool)
	for _, v := range meta.Values {
		if v.AutoGen != "" && mergedValues[v.Name] == "" {
			switch v.AutoGen {
			case "password":
				pw, err := genPassword()
				if err != nil {
					return fmt.Errorf("generating password for %s: %w", v.Name, err)
				}
				mergedValues[v.Name] = pw
				autoGenerated[v.Name] = true
			case "uuid":
				mergedValues[v.Name] = uuid.New().String()
				autoGenerated[v.Name] = true
			}
		}
	}

	// Ensure timezone has a default even if not declared in app.yaml
	if mergedValues["timezone"] == "" {
		mergedValues["timezone"] = "UTC"
	}

	// Validate required values
	for _, v := range meta.Values {
		if v.Required && mergedValues[v.Name] == "" {
			return fmt.Errorf("required value %q is not set and has no default", v.Name)
		}
	}

	// Add standard values
	mergedValues["hostname"] = m.cfg.Hostname
	mergedValues["domain"] = m.cfg.Network.Domain
	mergedValues["data_dir"] = m.cfg.DataPath(appName)
	mergedValues["app_name"] = appName
	mergedValues["network"] = m.cfg.Docker.DefaultNetwork
	if mergedValues["web_port"] == "" {
		mergedValues["web_port"] = strconv.Itoa(m.cfg.Network.WebPort)
	}

	// Add HTTPS status for all apps so templates can conditionally set protocol
	if m.cfg.Routing.Enabled && m.cfg.Routing.HTTPS.Enabled {
		mergedValues["https_enabled"] = "true"
		mergedValues["ca_cert_path"] = filepath.Join(m.cfg.DataPath("traefik"), "certs", "ca.crt")
	} else {
		mergedValues["https_enabled"] = "false"
		mergedValues["ca_cert_path"] = ""
	}

	// Auto-populate traefik-specific HTTPS values
	if appName == "traefik" && m.cfg.Routing.HTTPS.Enabled {
		mergedValues["acme_email"] = m.cfg.Routing.HTTPS.AcmeEmail
		mergedValues["certs_dir"] = filepath.Join(m.cfg.DataPath("traefik"), "certs")
	}

	// Generate local certificates for traefik
	if appName == "traefik" && m.cfg.Routing.HTTPS.Enabled {
		cm := NewCertManager(m.cfg.DataPath("traefik"))
		if err := cm.EnsureCerts(m.cfg.RoutingDomain()); err != nil {
			return fmt.Errorf("generating local certificates: %w", err)
		}
		slog.Info("Local certificates generated", "ca_cert", cm.CACertPath())
	}

	// Generate dashboard route for the homelabctl web UI
	if appName == "traefik" && m.cfg.Routing.Enabled {
		if err := GenerateDashboardRoute(m.cfg); err != nil {
			slog.Warn("Failed to generate dashboard route", "error", err)
		}
	}

	// Compute routing BEFORE rendering so templates can use routing_domain/routing_url
	var deployedRouting *DeployedRouting
	if m.cfg.Routing.Enabled && m.cfg.Routing.Provider == "traefik" {
		deployedRouting = computeRouting(m.cfg, appName, meta)
		if deployedRouting.Enabled && len(deployedRouting.Domains) > 0 {
			scheme := "http"
			if m.cfg.Routing.HTTPS.Enabled {
				scheme = "https"
			}
			mergedValues["routing_domain"] = deployedRouting.Domains[0]
			mergedValues["routing_url"] = fmt.Sprintf("%s://%s", scheme, deployedRouting.Domains[0])
		}
	}

	// Fallback routing values when routing is disabled (templates use missingkey=error)
	if mergedValues["routing_domain"] == "" {
		mergedValues["routing_domain"] = m.cfg.Hostname + "." + m.cfg.Network.Domain
	}
	if mergedValues["routing_url"] == "" {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		mergedValues["routing_url"] = fmt.Sprintf("%s://%s", scheme, mergedValues["routing_domain"])
	}

	// Render templates
	rendered, err := m.renderer.RenderAllFiles(appName, mergedValues)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	// Inject routing labels into rendered compose
	if deployedRouting != nil && deployedRouting.Enabled {
		labeler := NewRoutingLabeler(m.cfg)
		if compose, ok := rendered["docker-compose.yml"]; ok {
			modified, err := labeler.InjectLabels(compose, appName, deployedRouting)
			if err != nil {
				slog.Warn("Failed to inject routing labels", "app", appName, "error", err)
			} else {
				rendered["docker-compose.yml"] = modified
			}
		}
	}

	// Get static files
	staticFiles, err := m.renderer.CopyStaticFiles(appName)
	if err != nil {
		return fmt.Errorf("reading static files: %w", err)
	}

	if opts.DryRun {
		fmt.Println("Dry run — files that would be written:")
		for name, content := range rendered {
			fmt.Printf("\n--- %s ---\n%s", name, content)
		}
		for name := range staticFiles {
			fmt.Printf("\n--- %s (static) ---\n", name)
		}
		return nil
	}

	// Show confirmation summary unless --yes was passed
	if !opts.Confirm {
		printDeploySummary(appName, meta, mergedValues, autoGenerated)
		if !AskConfirmation("Proceed with deploy?") {
			return fmt.Errorf("deploy cancelled by user")
		}
	}

	// Ensure docker network exists
	if err := m.ensureNetwork(); err != nil {
		return err
	}

	// Create directories
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		return fmt.Errorf("creating app directory: %w", err)
	}
	dataDir := m.cfg.DataPath(appName)
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return fmt.Errorf("creating data directory: %w", err)
	}

	// Generate CA bundle for apps that need to trust the local CA
	if m.cfg.Routing.HTTPS.Enabled && mergedValues["ca_cert_path"] != "" {
		if err := generateCABundle(mergedValues["ca_cert_path"], dataDir); err != nil {
			slog.Warn("Failed to generate CA bundle", "app", appName, "error", err)
		}
	}

	// Write rendered files
	for name, content := range rendered {
		outPath := filepath.Join(appDir, name)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", name, err)
		}
		if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}

	// Write static files
	for name, data := range staticFiles {
		outPath := filepath.Join(appDir, name)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", name, err)
		}
		if err := os.WriteFile(outPath, data, 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}

	// Save deployment info
	deployed := &DeployedApp{
		Name:       appName,
		Template:   appName,
		Values:     mergedValues,
		DeployedAt: time.Now(),
		Version:    meta.Version,
		Routing:    deployedRouting,
	}
	infoData, err := yaml.Marshal(deployed)
	if err != nil {
		return fmt.Errorf("serializing deploy info: %w", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, ".homelabctl.yaml"), infoData, 0o600); err != nil {
		return fmt.Errorf("writing deploy info: %w", err)
	}

	// Run docker compose up
	fmt.Printf("Starting %s...\n", appName)
	var composeErr error
	if meta.RequiresBuild {
		_, composeErr = m.compose.UpWithBuild(appDir)
	} else {
		_, composeErr = m.compose.Up(appDir)
	}
	if composeErr != nil {
		// Clean up on failure so the user can retry without needing to remove first.
		_, _ = m.compose.Down(appDir)
		os.RemoveAll(appDir)
		return fmt.Errorf("starting containers: %w", composeErr)
	}

	// Print access information
	hostname := mergedValues["hostname"]
	domain := mergedValues["domain"]
	fqdn := hostname + "." + domain

	fmt.Printf("\nApp %s deployed successfully.\n\n", appName)
	for _, p := range meta.Ports {
		if p.ValueName != "" {
			if portVal, ok := mergedValues[p.ValueName]; ok {
				scheme := "http"
				if strings.Contains(strings.ToLower(p.Description), "https") {
					scheme = "https"
				}
				fmt.Printf("  %-20s %s://%s:%s\n", p.Description+":", scheme, fqdn, portVal)
			}
		} else {
			fmt.Printf("  %-20s :%d (container :%d)\n", p.Description+":", p.Host, p.Container)
		}
	}
	fmt.Printf("  %-20s %s\n", "Data:", m.cfg.DataPath(appName))

	// Show routing URLs
	if deployed.Routing != nil && deployed.Routing.Enabled && len(deployed.Routing.Domains) > 0 {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		for _, d := range deployed.Routing.Domains {
			fmt.Printf("  %-20s %s://%s\n", "URL:", scheme, d)
		}
	}

	fmt.Println()

	// Show post-deploy info if available
	if meta.PostDeployInfo != nil {
		printPostDeployInfo(meta.PostDeployInfo, mergedValues)
	}

	// Execute post-deploy hooks
	if meta.Hooks != nil {
		executeHooks(meta.Hooks.PostDeploy, mergedValues, m.runner)
	}

	// Invoke deploy callback (e.g. for Avahi CNAME publishing)
	if m.OnDeploy != nil {
		m.OnDeploy(appName, deployed.Routing)
	}

	return nil
}

// printDeploySummary shows what will be deployed before asking for confirmation.
func printDeploySummary(appName string, meta *AppMeta, mergedValues map[string]string, autoGenerated map[string]bool) {
	fmt.Printf("\n=== Deploy Summary ===\n\n")
	fmt.Printf("  App:      %s\n", appName)
	fmt.Printf("  Version:  %s\n", meta.Version)
	fmt.Println()

	// Port mappings
	if len(meta.Ports) > 0 {
		fmt.Println("  Ports:")
		for _, p := range meta.Ports {
			hostPort := fmt.Sprintf("%d", p.Host)
			if p.ValueName != "" {
				if v, ok := mergedValues[p.ValueName]; ok {
					hostPort = v
				}
			}
			fmt.Printf("    %s:%d/%s  (%s)\n", hostPort, p.Container, p.Protocol, p.Description)
		}
		fmt.Println()
	}

	// Volume mounts
	if len(meta.Volumes) > 0 {
		fmt.Println("  Volumes:")
		dataDir := mergedValues["data_dir"]
		for _, v := range meta.Volumes {
			fmt.Printf("    %s/%s -> %s  (%s)\n", dataDir, v.Name, v.Container, v.Description)
		}
		fmt.Println()
	}

	// Auto-generated secrets
	if len(autoGenerated) > 0 {
		fmt.Println("  Auto-generated secrets:")
		for name := range autoGenerated {
			fmt.Printf("    %s  [generated]\n", name)
		}
		fmt.Println()
	}
}

// AskConfirmation prompts the user for y/n and returns true if they confirm.
func AskConfirmation(prompt string) bool {
	fmt.Printf("%s [y/N]: ", prompt)
	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		answer := strings.TrimSpace(strings.ToLower(scanner.Text()))
		return answer == "y" || answer == "yes"
	}
	return false
}

// Remove removes a deployed app.
func (m *Manager) Remove(appName string, keepData bool) error {
	lock, err := m.acquireLock(appName)
	if err != nil {
		return err
	}
	defer m.releaseLock(lock)

	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}

	// Execute pre-remove hooks
	meta, ok := m.registry.Get(appName)
	if ok && meta.Hooks != nil {
		executeHooks(meta.Hooks.PreRemove, map[string]string{
			"app_name": appName,
			"hostname": m.cfg.Hostname,
			"domain":   m.cfg.Network.Domain,
			"data_dir": m.cfg.DataPath(appName),
		}, m.runner)
	}

	// Stop containers
	fmt.Printf("Stopping %s...\n", appName)
	if _, err := m.compose.Down(appDir); err != nil {
		fmt.Printf("Warning: failed to stop containers: %v\n", err)
	}

	// Remove app directory
	if err := os.RemoveAll(appDir); err != nil {
		return fmt.Errorf("removing app directory: %w", err)
	}

	// Invoke remove callback (e.g. for Avahi CNAME unpublishing)
	if m.OnRemove != nil {
		m.OnRemove(appName)
	}

	if !keepData {
		dataDir := m.cfg.DataPath(appName)
		if err := os.RemoveAll(dataDir); err != nil {
			// Containers often create root-owned files. Clean contents via Docker, then remove the dir.
			if _, dockerErr := m.runner.Run(m.cfg.Docker.Runtime, "run", "--rm",
				"-v", dataDir+":/data", "alpine", "sh", "-c", "rm -rf /data/*"); dockerErr != nil {
				return fmt.Errorf("removing data directory: %w (docker fallback also failed: %v)", err, dockerErr)
			}
			os.RemoveAll(dataDir)
		}
		fmt.Printf("App %s removed (including data).\n", appName)
	} else {
		fmt.Printf("App %s removed (data kept at %s).\n", appName, m.cfg.DataPath(appName))
	}

	return nil
}

// Start starts a deployed app's containers.
func (m *Manager) Start(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Start(appDir)
	return err
}

// Stop stops a deployed app's containers.
func (m *Manager) Stop(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Stop(appDir)
	return err
}

// Restart restarts a deployed app's containers.
func (m *Manager) Restart(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Restart(appDir)
	return err
}

// Status returns the container status for an app.
func (m *Manager) Status(appName string) (string, error) {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return "", fmt.Errorf("app %s is not deployed", appName)
	}
	result, err := m.compose.PS(appDir)
	if err != nil {
		return "", err
	}
	return result.Stdout, nil
}

// ListDeployed returns the names of all deployed apps.
func (m *Manager) ListDeployed() ([]string, error) {
	entries, err := os.ReadDir(m.cfg.AppsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var apps []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		infoPath := filepath.Join(m.cfg.AppsDir, entry.Name(), ".homelabctl.yaml")
		if _, err := os.Stat(infoPath); err == nil {
			apps = append(apps, entry.Name())
		}
	}
	return apps, nil
}

// GetDeployedInfo reads the deployment info for an app.
func (m *Manager) GetDeployedInfo(appName string) (*DeployedApp, error) {
	infoPath := filepath.Join(m.cfg.AppDir(appName), ".homelabctl.yaml")
	data, err := os.ReadFile(infoPath)
	if err != nil {
		return nil, fmt.Errorf("reading deploy info: %w", err)
	}
	var info DeployedApp
	if err := yaml.Unmarshal(data, &info); err != nil {
		return nil, fmt.Errorf("parsing deploy info: %w", err)
	}
	return &info, nil
}

// SaveDeployedInfo writes updated deployment info for an app.
func (m *Manager) SaveDeployedInfo(appName string, info *DeployedApp) error {
	infoPath := filepath.Join(m.cfg.AppDir(appName), ".homelabctl.yaml")
	data, err := yaml.Marshal(info)
	if err != nil {
		return fmt.Errorf("serializing deploy info: %w", err)
	}
	return os.WriteFile(infoPath, data, 0o600)
}

// printPostDeployInfo displays post-deploy information to the user.
func printPostDeployInfo(info *PostDeployInfo, values map[string]string) {
	fmt.Println("--- Post-Deploy Info ---")

	if info.AccessURL != "" {
		if rendered, err := renderTemplate(info.AccessURL, values); err == nil {
			fmt.Printf("  Access URL:    %s\n", rendered)
		}
	}

	if info.Credentials != "" {
		if rendered, err := renderTemplate(info.Credentials, values); err == nil {
			fmt.Printf("  Credentials:   %s\n", rendered)
		}
	}

	if len(info.Notes) > 0 {
		fmt.Println("  First-time setup:")
		for i, note := range info.Notes {
			if rendered, err := renderTemplate(note, values); err == nil {
				fmt.Printf("    %d. %s\n", i+1, rendered)
			}
		}
	}

	fmt.Println()
}

// renderTemplate renders a Go template string with the given values.
func renderTemplate(tmplStr string, values map[string]string) (string, error) {
	t, err := template.New("").Parse(tmplStr)
	if err != nil {
		return tmplStr, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, values); err != nil {
		return tmplStr, err
	}
	return buf.String(), nil
}

// GenerateDashboardRoute writes a traefik file-provider config that routes
// the bare routing domain to the homelabctl web dashboard on the host.
func GenerateDashboardRoute(cfg *config.Config) error {
	dynamicDir := filepath.Join(cfg.DataPath("traefik"), "dynamic")
	if err := os.MkdirAll(dynamicDir, 0o755); err != nil {
		return fmt.Errorf("creating dynamic directory: %w", err)
	}

	routingDomain := cfg.RoutingDomain()
	webPort := cfg.Network.WebPort

	hostRule := "`" + routingDomain + "`"

	var yml string
	if cfg.Routing.HTTPS.Enabled {
		yml = fmt.Sprintf(`http:
  routers:
    dashboard:
      rule: "Host(%[1]s)"
      service: dashboard
      entryPoints:
        - web
    dashboard-secure:
      rule: "Host(%[1]s)"
      service: dashboard
      entryPoints:
        - websecure
      tls: {}
  services:
    dashboard:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:%[2]d"
`, hostRule, webPort)
	} else {
		yml = fmt.Sprintf(`http:
  routers:
    dashboard:
      rule: "Host(%[1]s)"
      service: dashboard
      entryPoints:
        - web
  services:
    dashboard:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:%[2]d"
`, hostRule, webPort)
	}

	return os.WriteFile(filepath.Join(dynamicDir, "dashboard.yml"), []byte(yml), 0o644)
}

// executeHooks runs lifecycle hooks, logging errors but not failing the deploy.
func executeHooks(hooks []Hook, values map[string]string, runner *exec.Runner) {
	for _, hook := range hooks {
		switch hook.Type {
		case "exec":
			cmd, err := renderTemplate(hook.Command, values)
			if err != nil {
				slog.Warn("Hook: failed to render command template", "error", err)
				continue
			}
			slog.Info("Running post-deploy hook", "command", cmd)
			if _, err := runner.Run("sh", "-c", cmd); err != nil {
				slog.Warn("Post-deploy hook failed", "command", cmd, "error", err)
			}
		case "http":
			url, err := renderTemplate(hook.URL, values)
			if err != nil {
				slog.Warn("Hook: failed to render URL template", "error", err)
				continue
			}
			method := hook.Method
			if method == "" {
				method = "GET"
			}
			var bodyReader *bytes.Reader
			if hook.Body != "" {
				body, err := renderTemplate(hook.Body, values)
				if err != nil {
					slog.Warn("Hook: failed to render body template", "error", err)
					continue
				}
				bodyReader = bytes.NewReader([]byte(body))
			} else {
				bodyReader = bytes.NewReader(nil)
			}
			slog.Info("Running post-deploy HTTP hook", "method", method, "url", url)
			req, err := http.NewRequest(method, url, bodyReader)
			if err != nil {
				slog.Warn("Hook: failed to create request", "error", err)
				continue
			}
			if hook.Body != "" {
				req.Header.Set("Content-Type", "application/json")
			}
			client := &http.Client{Timeout: 30 * time.Second}
			resp, err := client.Do(req)
			if err != nil {
				slog.Warn("Post-deploy HTTP hook failed", "url", url, "error", err)
				continue
			}
			resp.Body.Close()
			if resp.StatusCode >= 400 {
				slog.Warn("Post-deploy HTTP hook returned error", "url", url, "status", resp.StatusCode)
			}
		}
	}
}

// generateCABundle creates a CA certificate bundle that includes the system CAs
// plus the homelabctl local CA. This allows containers to trust the self-signed
// wildcard certificate used for local HTTPS routing.
func generateCABundle(caCertPath, dataDir string) error {
	systemBundle, err := os.ReadFile("/etc/ssl/certs/ca-certificates.crt")
	if err != nil {
		return fmt.Errorf("reading system CA bundle: %w", err)
	}
	localCA, err := os.ReadFile(caCertPath)
	if err != nil {
		return fmt.Errorf("reading local CA cert: %w", err)
	}

	bundlePath := filepath.Join(dataDir, "ca-bundle.crt")
	bundle := make([]byte, 0, len(systemBundle)+1+len(localCA))
	bundle = append(bundle, systemBundle...)
	bundle = append(bundle, '\n')
	bundle = append(bundle, localCA...)
	if err := os.WriteFile(bundlePath, bundle, 0o644); err != nil {
		return fmt.Errorf("writing CA bundle: %w", err)
	}
	return nil
}
